### ISSUE TITLE
Github Pages

### ISSUE THREAD

**Issue by multimeric** [alexander-heimbuch/millidocs#1]
Would it be possible to explain how to get this theme to work on Github Pages? I gather the instructions on the readme are for local Jekyll, so I'm not sure if I should use `theme` or `remote-theme`, along with what page structure to use

**Comment by kajaschmidt** [comment]
Wanted to mention that the search bar does not seem to work

**Comment by alexander-heimbuch** [comment]
Sorry for the late response folks, Github didn't gave me any notification :/

@TMiguelT Unfortunately not. Github Pages only supports a fixed set of default themes. You have to build it locally and push the generated html to either a folder or a custom branch.

@kajaschmidt Can you give me some more details? A test page would be perfect.

**Comment by neumannjan** [comment]
>  Github Pages only supports a fixed set of default themes. You have to build it locally and push the generated html to either a folder or a custom branch.

Not true. Using `remote-theme` is enough. See [here](https://blog.github.com/2017-11-29-use-any-theme-with-github-pages/).

> Can you give me some more details? A test page would be perfect.

See your own demo. The search functionality is broken.

**Comment by alexander-heimbuch** [comment]
Thanks @kogli for the hints. I updated the theme, made a new release and also added a section for github pages.
